# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_functions', [dirname(__file__)])
        except ImportError:
            import _functions
            return _functions
        if fp is not None:
            try:
                _mod = imp.load_module('_functions', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _functions = swig_import_helper()
    del swig_import_helper
else:
    import _functions
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _functions.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _functions.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _functions.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _functions.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _functions.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _functions.SwigPyIterator_equal(self, x)

    def copy(self):
        return _functions.SwigPyIterator_copy(self)

    def next(self):
        return _functions.SwigPyIterator_next(self)

    def __next__(self):
        return _functions.SwigPyIterator___next__(self)

    def previous(self):
        return _functions.SwigPyIterator_previous(self)

    def advance(self, n):
        return _functions.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _functions.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _functions.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _functions.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _functions.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _functions.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _functions.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _functions.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _functions.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _functions.IntVector___nonzero__(self)

    def __bool__(self):
        return _functions.IntVector___bool__(self)

    def __len__(self):
        return _functions.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _functions.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _functions.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _functions.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _functions.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _functions.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _functions.IntVector___setitem__(self, *args)

    def pop(self):
        return _functions.IntVector_pop(self)

    def append(self, x):
        return _functions.IntVector_append(self, x)

    def empty(self):
        return _functions.IntVector_empty(self)

    def size(self):
        return _functions.IntVector_size(self)

    def swap(self, v):
        return _functions.IntVector_swap(self, v)

    def begin(self):
        return _functions.IntVector_begin(self)

    def end(self):
        return _functions.IntVector_end(self)

    def rbegin(self):
        return _functions.IntVector_rbegin(self)

    def rend(self):
        return _functions.IntVector_rend(self)

    def clear(self):
        return _functions.IntVector_clear(self)

    def get_allocator(self):
        return _functions.IntVector_get_allocator(self)

    def pop_back(self):
        return _functions.IntVector_pop_back(self)

    def erase(self, *args):
        return _functions.IntVector_erase(self, *args)

    def __init__(self, *args):
        this = _functions.new_IntVector(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _functions.IntVector_push_back(self, x)

    def front(self):
        return _functions.IntVector_front(self)

    def back(self):
        return _functions.IntVector_back(self)

    def assign(self, n, x):
        return _functions.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _functions.IntVector_resize(self, *args)

    def insert(self, *args):
        return _functions.IntVector_insert(self, *args)

    def reserve(self, n):
        return _functions.IntVector_reserve(self, n)

    def capacity(self):
        return _functions.IntVector_capacity(self)
    __swig_destroy__ = _functions.delete_IntVector
    __del__ = lambda self: None
IntVector_swigregister = _functions.IntVector_swigregister
IntVector_swigregister(IntVector)

class DoubleVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _functions.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _functions.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _functions.DoubleVector___bool__(self)

    def __len__(self):
        return _functions.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _functions.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _functions.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _functions.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _functions.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _functions.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _functions.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _functions.DoubleVector_pop(self)

    def append(self, x):
        return _functions.DoubleVector_append(self, x)

    def empty(self):
        return _functions.DoubleVector_empty(self)

    def size(self):
        return _functions.DoubleVector_size(self)

    def swap(self, v):
        return _functions.DoubleVector_swap(self, v)

    def begin(self):
        return _functions.DoubleVector_begin(self)

    def end(self):
        return _functions.DoubleVector_end(self)

    def rbegin(self):
        return _functions.DoubleVector_rbegin(self)

    def rend(self):
        return _functions.DoubleVector_rend(self)

    def clear(self):
        return _functions.DoubleVector_clear(self)

    def get_allocator(self):
        return _functions.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _functions.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _functions.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        this = _functions.new_DoubleVector(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _functions.DoubleVector_push_back(self, x)

    def front(self):
        return _functions.DoubleVector_front(self)

    def back(self):
        return _functions.DoubleVector_back(self)

    def assign(self, n, x):
        return _functions.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _functions.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _functions.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _functions.DoubleVector_reserve(self, n)

    def capacity(self):
        return _functions.DoubleVector_capacity(self)
    __swig_destroy__ = _functions.delete_DoubleVector
    __del__ = lambda self: None
DoubleVector_swigregister = _functions.DoubleVector_swigregister
DoubleVector_swigregister(DoubleVector)

class DoubleVector2(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DoubleVector2, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DoubleVector2, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _functions.DoubleVector2_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _functions.DoubleVector2___nonzero__(self)

    def __bool__(self):
        return _functions.DoubleVector2___bool__(self)

    def __len__(self):
        return _functions.DoubleVector2___len__(self)

    def __getslice__(self, i, j):
        return _functions.DoubleVector2___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _functions.DoubleVector2___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _functions.DoubleVector2___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _functions.DoubleVector2___delitem__(self, *args)

    def __getitem__(self, *args):
        return _functions.DoubleVector2___getitem__(self, *args)

    def __setitem__(self, *args):
        return _functions.DoubleVector2___setitem__(self, *args)

    def pop(self):
        return _functions.DoubleVector2_pop(self)

    def append(self, x):
        return _functions.DoubleVector2_append(self, x)

    def empty(self):
        return _functions.DoubleVector2_empty(self)

    def size(self):
        return _functions.DoubleVector2_size(self)

    def swap(self, v):
        return _functions.DoubleVector2_swap(self, v)

    def begin(self):
        return _functions.DoubleVector2_begin(self)

    def end(self):
        return _functions.DoubleVector2_end(self)

    def rbegin(self):
        return _functions.DoubleVector2_rbegin(self)

    def rend(self):
        return _functions.DoubleVector2_rend(self)

    def clear(self):
        return _functions.DoubleVector2_clear(self)

    def get_allocator(self):
        return _functions.DoubleVector2_get_allocator(self)

    def pop_back(self):
        return _functions.DoubleVector2_pop_back(self)

    def erase(self, *args):
        return _functions.DoubleVector2_erase(self, *args)

    def __init__(self, *args):
        this = _functions.new_DoubleVector2(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this

    def push_back(self, x):
        return _functions.DoubleVector2_push_back(self, x)

    def front(self):
        return _functions.DoubleVector2_front(self)

    def back(self):
        return _functions.DoubleVector2_back(self)

    def assign(self, n, x):
        return _functions.DoubleVector2_assign(self, n, x)

    def resize(self, *args):
        return _functions.DoubleVector2_resize(self, *args)

    def insert(self, *args):
        return _functions.DoubleVector2_insert(self, *args)

    def reserve(self, n):
        return _functions.DoubleVector2_reserve(self, n)

    def capacity(self):
        return _functions.DoubleVector2_capacity(self)
    __swig_destroy__ = _functions.delete_DoubleVector2
    __del__ = lambda self: None
DoubleVector2_swigregister = _functions.DoubleVector2_swigregister
DoubleVector2_swigregister(DoubleVector2)


def sysRHS(y):
    return _functions.sysRHS(y)
sysRHS = _functions.sysRHS

def euler_integrator(arg1, arg2):
    return _functions.euler_integrator(arg1, arg2)
euler_integrator = _functions.euler_integrator

def integrate(arg1, arg2, arg3):
    return _functions.integrate(arg1, arg2, arg3)
integrate = _functions.integrate
# This file is compatible with both classic and new-style classes.


