
#include <iostream>
#include <random>



int main(int argc, char const *argv[])
{
	const int seed = 1234;
	std::default_random_engine gen_uniform(seed);
	std::uniform_int_distribution<int> rand_uniform(0, 1);
	
	for (int i=0; i<20; i++)
		std::cout << rand_uniform(gen_uniform)*2-1 << ' ';
	std::cout << '\n';


	std::random_device rd;  //Will be used to obtain a seed for the random number engine
    std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
    std::uniform_int_distribution<> dis(0, 1);

    for (int n=0; n<20; ++n)
        //Use dis to transform the random unsigned int generated by gen into an int in [1, 6]
        std::cout << dis(gen)*2-1 << ' ';
    std::cout << '\n';

	return 0;
}